# Generated by Django 5.0.4 on 2024-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('comapanyName', models.CharField(max_length=255)),
                ('comapanyUrl', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
