# Generated by Django 5.0.4 on 2024-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='comapanyName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='comapanyUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
