# Generated by Django 5.0.4 on 2024-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analyzer', '0002_analysis_rate_analysis_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='employer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='task',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
