# Generated by Django 5.0.4 on 2024-06-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analyzer', '0003_analysis_employer_analysis_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='task',
            field=models.IntegerField(default=2),
        ),
    ]
